language: php
php:
  - 7.2
install:
  - composer install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
notifications:
  email:
    - boontat_puah@commontown.com
  on_success: always # default: change
  on_failure: always # default: always